# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='words',
            name='word',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
