# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20161012_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AlterField(
            model_name='words',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='words',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='words',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
