# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20161117_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp',
            new_name='Entity',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.RenameField(
            model_name='words',
            old_name='temp',
            new_name='entity',
        ),
    ]
