# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20161127_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '----'), ('male', 'Male'), ('female', 'Female'), ('genderless', 'Genderless')], default='', max_length=10, null=True),
        ),
    ]
