# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20161117_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
