# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='ISO_2',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
